server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JoelMaciel/BANK-CONFIG-SERVER-REPO
          default-label: main
          username: JoelMaciel
          password: ${PASSWORD_GIT_REPO}

bank:
  configServer:
    username: configserver
    password: ${CONFIG_PASS}
  serviceRegistry:
    username: serviceregistry
    password: ${PASSWORD}


eureka:
  client:
    service-url:
      defaultZone: 'http://${bank.serviceRegistry.username}:${PASSWORD}@localhost:8761/eureka'
  instance:
    hostname: localhost
